class Bus {
  final String name;
  final String description;
  final String image;
  final List<String> places;

  Bus(
      {required this.name,
      required this.description,
      required this.image,
      required this.places});
}

List<Bus> buses = [
  Bus(
    name: 'Akash',
    description:
        "Golap Shah Mazar ⇄ GPO ⇄ Paltan ⇄ Kakrail ⇄ Shantinagar ⇄ Malibagh Moor ⇄ Mouchak ⇄ Malibagh Railgate ⇄ Hazipara ⇄ Rampura Bazar ⇄ Rampura Bridge ⇄ Merul ⇄ Badda ⇄ Shahjadpur ⇄ Bashtola ⇄ Notun Bazar ⇄ Nadda ⇄ Bashundhara ⇄ Jamuna Future Park ⇄ Kuril Bishwa Road ⇄ Khilkhet ⇄ Airport ⇄ Jashimuddin (Uttara) ⇄ Rajlakshmi ⇄ Azampur ⇄ House Building ⇄ Abdullahpur ⇄ Tongi",
    image: 'assets/images/ahad.jpeg',
    places: [
      'Kadamtali',
      'Keraniganj',
      'Babubazar',
      'Naya Baza',
      'Golap Shah Mazar',
      'GPO',
      'Paltan',
      'Kakrail',
      'Shantinagar',
      'Malibagh Moor',
      'Mouchak',
      'Malibagh Railgate',
      'Hazipara',
      'Rampura Bazar',
      'Merul',
      'Badda',
      'Shahjadpur',
      'Bashtola',
      'Notun Bazar',
      'Nadda',
      'Bashundhara',
      'Jamuna Future Park',
      'Kuril Bishwa Road',
      'Khilkhet',
      'Airport',
      'Jashimuddin',
      'Rajlakshmi',
      'Azampur',
      'House Building',
      'Abdullahpur',
      'Tongi',
    ],
  ),
  Bus(
    name: 'Transilva',
    description:
        "Mirpur 1 ⇄ Ansar Camp ⇄ Technical ⇄ Kallyanpur ⇄ Shyamoli ⇄ Shishu Mela ⇄ College Gate ⇄ Asad Gate ⇄ Dhanmondi 27 ⇄ Dhanmondi 32 ⇄ Kalabagan ⇄ Science Lab ⇄ Bata Signal ⇄ Shahbag ⇄ Matsya Bhaban ⇄ High Court ⇄ Press Club Paltan ⇄ GPO ⇄ Gulistan ⇄ Motijheel ⇄ Sayedabad ⇄ Janapath Moor ⇄ Jatrabari",
    image: 'assets/images/bihongo.jpeg',
    places: [
      'Mirpur 1',
      'Ansar Camp',
      'Technical',
      'Kallyanpur',
      'Shyamoli',
      'Shishu Mela',
      'College Gate',
      'Asad Gate',
      'Dhanmondi 27',
      'Dhanmondi 32',
      'Kalabagan',
      'Science Lab',
      'Bata Signal',
      'Shahbag',
      'Matsya Bhaban',
      'High Court',
      'Press Club Paltan',
      'GPO',
      'Gulistan',
      'Motijheel',
      'Sayedabad',
      'Janapath Moor',
      'Jatrabari'
    ],
  ),
  Bus(
    name: 'MTCL-2',
    description:
        "Mohammadpur ⇄ Asad Gate ⇄ Dhanmondi 27 ⇄ Dhanmondi 32 ⇄ Shukrabad ⇄ Kalabagan ⇄ City College ⇄ Science Lab ⇄ Bata Signal ⇄ Shahbag ⇄ Matsya Bhaban – High Court ⇄ Press Club ⇄ Paltan ⇄ GPO ⇄ Gulistan ⇄ Motijheel ⇄ Arambagh Kingdom",
    image: 'assets/images/bolaka.jpeg',
    places: [
      'Mohammadpur',
      'Asad Gate',
      'Dhanmondi 27',
      'Dhanmondi 32',
      'Shukrabad',
      'Kalabagan',
      'City College',
      'Science Lab',
      'Bata Signal',
      'Press Club',
      'Paltan',
      'GPO',
      'Gulistan',
      'Motijheel',
      'Arambagh Kingdom',
    ],
  ),
  Bus(
    name: 'Airport Bangabandhu Avenue',
    description:
        "Fulbaria ⇄ Golap Shah Mazar ⇄ GPO ⇄ Paltan ⇄ Press Club ⇄ High Court ⇄ Matsya Bhaban ⇄ Shahbag ⇄ Bangla Motor ⇄ Kawran Bazar ⇄ Farmgate ⇄ Bijoy Sarani ⇄ Jahangir Gate ⇄ Mohakhali ⇄ Chairman Bari ⇄ Sainik Club ⇄ Banani ⇄ Kakali ⇄ Staff Road ⇄ MES ⇄ Shewra ⇄ Kuril Bishwa Road ⇄ Khilkhet ⇄ Airport ⇄ Jashimuddin (Uttara) ⇄ Rajlakshmi ⇄ Azampur ⇄ House Building ⇄ Abdullahpur",
    image: 'assets/images/dhakachaka.jpeg',
    places: [
      'Fulbaria',
      'Golap Shah Mazar',
      'GPO',
      'Paltan',
      'Press Club',
      'Shahbag',
      'Bangla Motor',
      'Kawran Bazar',
      'Farmgate',
      'Bijoy Sarani',
      'Jahangir Gate',
      'Mohakhali',
      'Chairman Bari',
      'Sainik Club',
      'Banani',
      'Kakali',
      'Kuril Bishwa Road',
      'Khilkhet',
      'Airport',
      'Jashimuddin',
      'Azampur',
      'House Building',
      'Abdullahpur',
    ],
  ),
  Bus(
    name: 'Alif',
    description:
        "Mirpur 14 ⇄ Mirpur 10 ⇄ Mirpur 2 ⇄ Sony Cenema Hall ⇄ Mirpur 1 ⇄ Mazar Road ⇄ Konabari ⇄ Rupnagar ⇄ Beribadh ⇄ Birulia ⇄ Ashulia ⇄ Zirabo ⇄ Fantasy Kingdom ⇄ Nandan Park",
    image: 'assets/images/dhakanogor.jpeg',
    places: [
      'Mirpur 14',
      'Mirpur 10',
      'Mirpur 2',
      'Sony Cinema Hall',
      'Mirpur 1',
      'Mazar Road',
      'Konabari',
      'Rupnagar',
      'Beribadh',
      'Birulia',
      'Ashulia',
      'Zirabo',
      'Fantasy Kingdom',
      'Nandan Park',
    ],
  ),
  Bus(
    name: 'Mirpur Mission',
    description:
        "Chiriyakhana ⇄ Mirpur 1 ⇄ Khamar Bari ⇄ Farmgate ⇄ Press Club ⇄ Motijheel",
    image: 'assets/images/himachal.jpeg',
    places: [
      'Chiriyakhana',
      'Mirpur 1',
      'Khamar Bari',
      'Farmgate',
      'Press Club',
      'Motijheel',
    ],
  ),
  Bus(
    name: '8 No. Bus',
    description:
        "Jatrabari ⇄ Janapath Moor ⇄ Sayedabad ⇄ Motijheel ⇄ Dainik Bangla Moor ⇄ Paltan ⇄ Press Club ⇄ Matsya Bhaban ⇄ High Court ⇄ Shahbag ⇄ Bangla Motor ⇄ Kawran Bazar ⇄ Farmgate ⇄ Khamar Bari ⇄ Asad Gate ⇄ College Gate ⇄ Shishu Mela ⇄ Shyamoli ⇄ Kallyanpur ⇄ Technical ⇄ Gabtoli",
    image: 'assets/images/midline.jpeg',
    places: [
      'Jatrabari',
      'Janapath Moor',
      'Sayedabad',
      'Motijheel',
      'Dainik Bangla Moor',
      'Paltan',
      'Press Club',
      'Matsya Bhaban',
      'High Court',
      'Shahbag',
      'Bangla Motor',
      'Kawran Bazar',
      'Farmgate',
      'Khamar Bari',
      'Asad Gate',
      'College Gate',
      'Shishu Mela',
      'Shyamoli',
      'Kallyanpur',
      'Technical',
      'Gabtoli',
    ],
  ),
  Bus(
    name: '9 No. Bus',
    description:
        'College Gate ⇄ Shishu Mela ⇄ Shyamoli ⇄ Kallyanpur ⇄ Darussalam ⇄ Technical ⇄ Bangla College ⇄ Tolarbag ⇄ Ansar Camp ⇄ Mirpur 1 ⇄ Sony Cinema Hall ⇄ Mirpur 2 ⇄ Proshika Moor ⇄ Pallabi ⇄ Mirpur 12',
    image: 'assets/images/hihongo.jpeg',
    places: [
      'College Gate',
      ' Shishu Mela',
      'Shyamoli',
      'Kallyanpur',
      'Darussalam',
      'Technical',
      'Bangla College',
      'Tolarbag',
      'Ansar Camp',
      'Mirpur 1',
      'Sony Cinema Hall',
      'Mirpur 2',
      'Proshika Moor',
      'Pallabi',
      'Mirpur 12',
    ],
  ),
  Bus(
    name: "7 No. Bus",
    description:
        "Gabtoli ⇄ Technical ⇄ Kallyanpur ⇄ Shyamoli ⇄ Shishu Mela ⇄ College Gate ⇄ Asad Gate ⇄ Dhanmondi 27 ⇄ Dhanmondi 32 ⇄ Kalabagan ⇄ Science Lab ⇄ Katabon ⇄ Shahbag ⇄ High Court ⇄ Press Club ⇄ Paltan ⇄ GPO ⇄ Golap Shah Mazar ⇄ Gulistan ⇄ Naya Bazar ⇄ Ray Saheb Bazar ⇄ Sadarghat",
    image: 'assets/images/rida.jpeg',
    places: [
      'Gabtoli',
      'Technical',
      'Kallyanpur',
      'Shyamoli',
      'Shishu Mela',
      'College Gate',
      'Asad Gate',
      'Dhanmondi 27',
      'Dhanmondi 32',
      'Kalabagan',
      'Science Lab',
      'Katabon',
      'Shahbag',
      'High Court',
      'Press Club',
      'Paltan',
      'GPO',
      'Golap Shah Mazar',
      'Gulistan',
      'Naya Bazar',
      'Ray Saheb Bazar',
      'Sadarghat',
    ],
  ),
  Bus(
    name: '6 No. Bus',
    description:
        'Kamalapur ⇄ Motijheel ⇄ Gulistan ⇄ GPO ⇄ Paltan ⇄ Kakrail ⇄ Shantinagar ⇄ Malibagh Moor ⇄ Mouchak ⇄ Mogbazar ⇄ Kawran Bazar ⇄ Farmgate ⇄ Jahangir Gate ⇄ Bijoy Sarani ⇄ Mohakhali ⇄ Gulshan 1 ⇄ Gulshan 2 ⇄ Notun Bazar',
    image: 'assets/images/savar.jpeg',
    places: [
      'Kamalapur',
      'Motijheel',
      'Gulistan',
      'GPO',
      'Paltan',
      'Kakrail',
      'Shantinagar',
      ' Malibagh Moor',
      'Mouchak',
      'Mogbazar',
      'Kawran Bazar',
      'Farmgate',
      'Jahangir Gate',
      'Bijoy Sarani',
      'Mohakhali',
      'Gulshan 1',
      'Gulshan 2',
      'Notun Bazar',
    ],
  ),
  Bus(
    name: 'Raida',
    description:
        'Postogola ⇄ Dholairpar ⇄ Jatrabari ⇄ Janapath Moor ⇄ Sayedabad ⇄ Mugdapara ⇄ Bashabo ⇄ Khilgaon ⇄ Malibagh Railgate ⇄ Rampura Bazar ⇄ Rampura Bridge ⇄ Merul ⇄ Badda ⇄ Uttar Badda ⇄ Bashtola ⇄ Notun Bazar ⇄ Nadda ⇄ Bashundhara ⇄ Jamuna Future Park ⇄ Kuril Chourasta ⇄ Kuril Bishwa Road ⇄ Khilkhet ⇄ Airport ⇄ Jashimuddin (Uttara) ⇄ Rajlakshmi ⇄ Azampur ⇄ House Building ⇄ Dia Bari',
    image: 'assets/images/rida.jpeg',
    places: [
      'Postogola',
      'Dholairpar',
      'Jatrabari',
      'Janapath Moor',
      'Sayedabad',
      'Mugdapara',
      'Bashabo',
      'Khilgaon',
      'Malibagh Railgate',
      'Rampura Bazar',
      'Rampura Bridge',
      'Merul',
      'Badda',
      'Uttar BaddaUttar Badda',
      'Bashtola',
      'Notun Bazar',
      'Nadda',
      'Bashundhara',
      'Jamuna Future Park',
      'Kuril Chourasta',
      'Kuril Bishwa Road',
      'Khilkhet',
      'Airport',
      'Jashimuddin',
      'Rajlakshmi',
      'Azampur',
      'House Building',
      'Dia Bari',
      
    ],
  ),
  Bus(
    name: 'Bikash',
    description:
        'Azimpur ⇄ Nilkhet ⇄ New Market ⇄ City College ⇄ Kalabagan ⇄ Dhanmondi 27 ⇄ Dhanmondi 32 ⇄ Khamar Bari ⇄ Farmgate ⇄ Jahangir Gate ⇄ Mohakhali ⇄ Sainik Club ⇄ Banani ⇄ Kakali ⇄ Kuril Bishwa Road ⇄ Khilkhet ⇄ Airport ⇄ Abdullahpur ⇄ Kamarpara',
    image: 'assets/images/bikash.jpg',
    places: [
      'Azimpur',
      'Nilkhet',
      'New Market',
      'City College',
      'Kalabagan',
      'Dhanmondi 27',
      'Dhanmondi 32',
      'Khamar Bari',
      'Farmgate',
      'Jahangir Gate',
      'Mohakhali',
      'Sainik Club',
      'Banani',
      'Kakali',
      'Kuril Bishwa Road',
      'Khilkhet',
      'Airport',
      'Abdullahpur',
      'Kamarpara',
    ],
  ),
  Bus(
    name: 'Borak',
    description:
        'Palashi ⇄ Meghna Ghat',
    image: 'assets/images/borak.jpeg',
    places: [
      'Palashi',
      'Meghna Ghat',
    ],
  ),
];
